import Head from 'next/head';
import Navbar from '../components/nav';

export default function Home({ posts }) {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navbar />
			<main className='container'>
				<div className='row'>
					{posts.map((post) => (
						<div key={post.id} className='col-3'>
							<h1> {post.title} </h1>
							<p> {post.body} </p>
						</div>
					))}
				</div>
			</main>
		</div>
	);
}

export async function getStaticProps() {
	const response = await fetch('https://jsonplaceholder.typicode.com/posts');
	const data = await response.json();

	return {
		props: {
			posts: data,
		},
	};
}
