import Link from 'next/link';
import Head from 'next/head';
import Navbar from '../components/nav';

export default function Home({ posts }) {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navbar />
			<main className='container'>
				<div className='row'>
					{posts.map((post) => (
						<div key={post.id} className='col-3 card'>
							<div className='card-body'>
								<h1 className='display-6 card-title'>
									{post.title.substring(0, 10)}...
								</h1>
								<p> {post.body.substring(0, 20)}... </p>
								<Link href={`/post/${post.id}`}>
									<button className='btn btn-primary'>Click me</button>
								</Link>
							</div>
						</div>
					))}
				</div>
			</main>
		</div>
	);
}

export async function getStaticProps() {
	const response = await fetch('https://jsonplaceholder.typicode.com/posts');
	const data = await response.json();

	return {
		props: {
			posts: data,
		},
	};
}
